In [1]:
import requests
import json
import pandas as pd
import regex as re
import os
import numpy as np

In [2]:
import os
from dotenv import load_dotenv

In [3]:
url = "https://api.bls.gov/publicAPI/v2/timeseries/data/"
headers = {'Content-type': 'application/json'}
api_key = os.getenv('PROJECT_API_KEY')

In [4]:
load_dotenv()
api_key = os.getenv('PROJECT_API_KEY')

if not api_key:
    print("API key not found!")
else:
    print(f"API key loaded")

API key loaded

In [5]:
item_code = {
'APU0000701111',
 'APU0000701312',
 'APU0000701322',
 'APU0000702111',
 'APU0000702212',
 'APU0000702421',
 'APU0000703111',
 'APU0000703112',
 'APU0000703113',
 'APU0000703213',
 'APU0000703311',
 'APU0000703432',
 'APU0000703511',
 'APU0000703512',
 'APU0000703613',
 'APU0000704111',
 'APU0000704211',
 'APU0000704212',
 'APU0000704312',
 'APU0000706111',
 'APU0000706212',
 'APU0000708111',
 'APU0000709112',
 'APU0000710211',
 'APU0000710212',
 'APU0000710411',
 'APU0000711211',
 'APU0000711311',
 'APU0000711411',
 'APU0000711412',
 'APU0000711415',
 'APU0000712112',
 'APU0000712211',
 'APU0000712311',
 'APU0000713111',
 'APU0000714221',
 'APU0000714233',
 'APU0000715211',
 'APU0000717311',
 'APU0000718311',
#  'APU0000720111',
#  'APU0000720222',
#  'APU0000720311',
 'APU0000FC1101',
#  'APU0000FC2101',
#  'APU0000FC3101',
#  'APU0000FC4101',
 'APU0000FD2101',
 'APU0000FD3101',
#  'APU0000FD4101',
 'APU0000FF1101',
 'APU0000FJ1101',
 'APU0000FJ4101',
 'APU0000FL2101',
 'APU0000FN1101',
 'APU0000FN1102',
 'APU0000FS1101'
}

In [6]:
data = {
    "seriesid": list(item_code),
    "startyear": "2024",
    "endyear": "2025",
    "registrationkey": api_key
}

response = requests.post(url, data=json.dumps(data), headers=headers)
response_data = response.json()

if response_data.get('status') == 'REQUEST_SUCCEEDED':
    if 'series' in response_data['Results'] and response_data['Results']['series']:
        for series_data in response_data['Results']['series']:
            print(f"Data for series ID {series_data['seriesID']}: {series_data['data'][:5]}")  # Print first 5 data points
    else:
        print("No data available for the provided series IDs.")
else:
    print(f"Failed to fetch data. Status: {response_data.get('status')}")

Data for series ID APU0000FF1101: [{'year': '2025', 'period': 'M07', 'periodName': 'July', 'latest': 'true', 'value': '4.204', 'footnotes': [{}]}, {'year': '2025', 'period': 'M06', 'periodName': 'June', 'value': '4.239', 'footnotes': [{}]}, {'year': '2025', 'period': 'M05', 'periodName': 'May', 'value': '4.216', 'footnotes': [{}]}, {'year': '2025', 'period': 'M04', 'periodName': 'April', 'value': '4.180', 'footnotes': [{}]}, {'year': '2025', 'period': 'M03', 'periodName': 'March', 'value': '4.160', 'footnotes': [{}]}]
Data for series ID APU0000703432: [{'year': '2025', 'period': 'M07', 'periodName': 'July', 'latest': 'true', 'value': '8.188', 'footnotes': [{}]}, {'year': '2025', 'period': 'M06', 'periodName': 'June', 'value': '8.016', 'footnotes': [{}]}, {'year': '2025', 'period': 'M05', 'periodName': 'May', 'value': '7.729', 'footnotes': [{}]}, {'year': '2025', 'period': 'M04', 'periodName': 'April', 'value': '7.733', 'footnotes': [{}]}, {'year': '2025', 'period': 'M03', 'periodName': 'March', 'value': '7.601', 'footnotes': [{}]}]
Data for series ID APU0000FL2101: [{'year': '2025', 'period': 'M07', 'periodName': 'July', 'latest': 'true', 'value': '3.006', 'footnotes': [{}]}, {'year': '2025', 'period': 'M06', 'periodName': 'June', 'value': '2.951', 'footnotes': [{}]}, {'year': '2025', 'period': 'M05', 'periodName': 'May', 'value': '2.994', 'footnotes': [{}]}, {'year': '2025', 'period': 'M04', 'periodName': 'April', 'value': '2.915', 'footnotes': [{}]}, {'year': '2025', 'period': 'M03', 'periodName': 'March', 'value': '2.923', 'footnotes': [{}]}]
Data for series ID APU0000704212: [{'year': '2025', 'period': 'M07', 'periodName': 'July', 'latest': 'true', 'value': '4.691', 'footnotes': [{}]}, {'year': '2025', 'period': 'M06', 'periodName': 'June', 'value': '4.618', 'footnotes': [{}]}, {'year': '2025', 'period': 'M05', 'periodName': 'May', 'value': '4.601', 'footnotes': [{}]}, {'year': '2025', 'period': 'M04', 'periodName': 'April', 'value': '4.609', 'footnotes': [{}]}, {'year': '2025', 'period': 'M03', 'periodName': 'March', 'value': '4.771', 'footnotes': [{}]}]
Data for series ID APU0000702111: [{'year': '2025', 'period': 'M07', 'periodName': 'July', 'latest': 'true', 'value': '1.851', 'footnotes': [{}]}, {'year': '2025', 'period': 'M06', 'periodName': 'June', 'value': '1.864', 'footnotes': [{}]}, {'year': '2025', 'period': 'M05', 'periodName': 'May', 'value': '1.876', 'footnotes': [{}]}, {'year': '2025', 'period': 'M04', 'periodName': 'April', 'value': '1.913', 'footnotes': [{}]}, {'year': '2025', 'period': 'M03', 'periodName': 'March', 'value': '1.880', 'footnotes': [{}]}]
Data for series ID APU0000FD3101: [{'year': '2025', 'period': 'M07', 'periodName': 'July', 'latest': 'true', 'value': '4.333', 'footnotes': [{}]}, {'year': '2025', 'period': 'M06', 'periodName': 'June', 'value': '4.264', 'footnotes': [{}]}, {'year': '2025', 'period': 'M05', 'periodName': 'May', 'value': '4.220', 'footnotes': [{}]}, {'year': '2025', 'period': 'M04', 'periodName': 'April', 'value': '4.244', 'footnotes': [{}]}, {'year': '2025', 'period': 'M03', 'periodName': 'March', 'value': '4.341', 'footnotes': [{}]}]
Data for series ID APU0000FJ4101: [{'year': '2025', 'period': 'M07', 'periodName': 'July', 'latest': 'true', 'value': '1.556', 'footnotes': [{}]}, {'year': '2025', 'period': 'M06', 'periodName': 'June', 'value': '1.494', 'footnotes': [{}]}, {'year': '2025', 'period': 'M05', 'periodName': 'May', 'value': '1.577', 'footnotes': [{}]}, {'year': '2025', 'period': 'M04', 'periodName': 'April', 'value': '1.538', 'footnotes': [{}]}, {'year': '2025', 'period': 'M03', 'periodName': 'March', 'value': '1.520', 'footnotes': [{}]}]
Data for series ID APU0000703512: [{'year': '2025', 'period': 'M07', 'periodName': 'July', 'latest': 'true', 'value': '8.706', 'footnotes': [{}]}, {'year': '2025', 'period': 'M06', 'periodName': 'June', 'value': '8.394', 'footnotes': [{}]}, {'year': '2025', 'period': 'M05', 'periodName': 'May', 'value': '8.199', 'footnotes': [{}]}, {'year': '2025', 'period': 'M04', 'periodName': 'April', 'value': '8.126', 'footnotes': [{}]}, {'year': '2025', 'period': 'M03', 'periodName': 'March', 'value': '8.155', 'footnotes': [{}]}]
Data for series ID APU0000703511: [{'year': '2025', 'period': 'M07', 'periodName': 'July', 'latest': 'true', 'value': '8.690', 'footnotes': [{}]}, {'year': '2025', 'period': 'M06', 'periodName': 'June', 'value': '8.457', 'footnotes': [{}]}, {'year': '2025', 'period': 'M05', 'periodName': 'May', 'value': '8.401', 'footnotes': [{}]}, {'year': '2025', 'period': 'M04', 'periodName': 'April', 'value': '8.627', 'footnotes': [{}]}, {'year': '2025', 'period': 'M03', 'periodName': 'March', 'value': '8.554', 'footnotes': [{}]}]
Data for series ID APU0000712112: [{'year': '2025', 'period': 'M07', 'periodName': 'July', 'latest': 'true', 'value': '0.978', 'footnotes': [{}]}, {'year': '2025', 'period': 'M06', 'periodName': 'June', 'value': '0.981', 'footnotes': [{}]}, {'year': '2025', 'period': 'M05', 'periodName': 'May', 'value': '0.958', 'footnotes': [{}]}, {'year': '2025', 'period': 'M04', 'periodName': 'April', 'value': '0.967', 'footnotes': [{}]}, {'year': '2025', 'period': 'M03', 'periodName': 'March', 'value': '0.950', 'footnotes': [{}]}]
Data for series ID APU0000706212: [{'year': '2025', 'period': 'M07', 'periodName': 'July', 'latest': 'true', 'value': '1.799', 'footnotes': [{}]}, {'year': '2025', 'period': 'M06', 'periodName': 'June', 'value': '1.815', 'footnotes': [{}]}, {'year': '2025', 'period': 'M05', 'periodName': 'May', 'value': '1.785', 'footnotes': [{}]}, {'year': '2025', 'period': 'M04', 'periodName': 'April', 'value': '1.789', 'footnotes': [{}]}, {'year': '2025', 'period': 'M03', 'periodName': 'March', 'value': '1.805', 'footnotes': [{}]}]
Data for series ID APU0000711411: [{'year': '2025', 'period': 'M07', 'periodName': 'July', 'latest': 'true', 'value': '1.726', 'footnotes': [{}]}, {'year': '2025', 'period': 'M06', 'periodName': 'June', 'value': '1.715', 'footnotes': [{}]}, {'year': '2025', 'period': 'M05', 'periodName': 'May', 'value': '1.675', 'footnotes': [{}]}, {'year': '2025', 'period': 'M04', 'periodName': 'April', 'value': '1.699', 'footnotes': [{}]}, {'year': '2025', 'period': 'M03', 'periodName': 'March', 'value': '1.695', 'footnotes': [{}]}]
Data for series ID APU0000701312: [{'year': '2025', 'period': 'M07', 'periodName': 'July', 'latest': 'true', 'value': '1.068', 'footnotes': [{}]}, {'year': '2025', 'period': 'M06', 'periodName': 'June', 'value': '1.061', 'footnotes': [{}]}, {'year': '2025', 'period': 'M05', 'periodName': 'May', 'value': '1.067', 'footnotes': [{}]}, {'year': '2025', 'period': 'M04', 'periodName': 'April', 'value': '1.031', 'footnotes': [{}]}, {'year': '2025', 'period': 'M03', 'periodName': 'March', 'value': '1.038', 'footnotes': [{}]}]
Data for series ID APU0000703113: [{'year': '2025', 'period': 'M07', 'periodName': 'July', 'latest': 'true', 'value': '8.035', 'footnotes': [{}]}, {'year': '2025', 'period': 'M06', 'periodName': 'June', 'value': '7.672', 'footnotes': [{}]}, {'year': '2025', 'period': 'M05', 'periodName': 'May', 'value': '7.688', 'footnotes': [{}]}, {'year': '2025', 'period': 'M04', 'periodName': 'April', 'value': '7.551', 'footnotes': [{}]}, {'year': '2025', 'period': 'M03', 'periodName': 'March', 'value': '7.476', 'footnotes': [{}]}]
Data for series ID APU0000710212: [{'year': '2025', 'period': 'M07', 'periodName': 'July', 'latest': 'true', 'value': '6.041', 'footnotes': [{}]}, {'year': '2025', 'period': 'M06', 'periodName': 'June', 'value': '5.999', 'footnotes': [{}]}, {'year': '2025', 'period': 'M05', 'periodName': 'May', 'value': '5.908', 'footnotes': [{}]}, {'year': '2025', 'period': 'M04', 'periodName': 'April', 'value': '5.743', 'footnotes': [{}]}, {'year': '2025', 'period': 'M03', 'periodName': 'March', 'value': '5.737', 'footnotes': [{}]}]
Data for series ID APU0000FJ1101: [{'year': '2025', 'period': 'M07', 'periodName': 'July', 'latest': 'true', 'value': '3.662', 'footnotes': [{}]}, {'year': '2025', 'period': 'M06', 'periodName': 'June', 'value': '3.592', 'footnotes': [{}]}, {'year': '2025', 'period': 'M05', 'periodName': 'May', 'value': '3.777', 'footnotes': [{}]}, {'year': '2025', 'period': 'M04', 'periodName': 'April', 'value': '3.850', 'footnotes': [{}]}, {'year': '2025', 'period': 'M03', 'periodName': 'March', 'value': '3.851', 'footnotes': [{}]}]
Data for series ID APU0000717311: [{'year': '2025', 'period': 'M07', 'periodName': 'July', 'latest': 'true', 'value': '8.414', 'footnotes': [{}]}, {'year': '2025', 'period': 'M06', 'periodName': 'June', 'value': '8.132', 'footnotes': [{}]}, {'year': '2025', 'period': 'M05', 'periodName': 'May', 'value': '7.931', 'footnotes': [{}]}, {'year': '2025', 'period': 'M04', 'periodName': 'April', 'value': '7.536', 'footnotes': [{}]}, {'year': '2025', 'period': 'M03', 'periodName': 'March', 'value': '7.385', 'footnotes': [{}]}]
Data for series ID APU0000703111: [{'year': '2025', 'period': 'M07', 'periodName': 'July', 'latest': 'true', 'value': '6.338', 'footnotes': [{}]}, {'year': '2025', 'period': 'M06', 'periodName': 'June', 'value': '6.103', 'footnotes': [{}]}, {'year': '2025', 'period': 'M05', 'periodName': 'May', 'value': '6.018', 'footnotes': [{}]}, {'year': '2025', 'period': 'M04', 'periodName': 'April', 'value': '5.996', 'footnotes': [{}]}, {'year': '2025', 'period': 'M03', 'periodName': 'March', 'value': '5.854', 'footnotes': [{}]}]
Data for series ID APU0000709112: [{'year': '2025', 'period': 'M07', 'periodName': 'July', 'latest': 'true', 'value': '4.162', 'footnotes': [{}]}, {'year': '2025', 'period': 'M06', 'periodName': 'June', 'value': '4.029', 'footnotes': [{}]}, {'year': '2025', 'period': 'M05', 'periodName': 'May', 'value': '4.022', 'footnotes': [{}]}, {'year': '2025', 'period': 'M04', 'periodName': 'April', 'value': '4.074', 'footnotes': [{}]}, {'year': '2025', 'period': 'M03', 'periodName': 'March', 'value': '4.050', 'footnotes': [{}]}]
Data for series ID APU0000712211: [{'year': '2025', 'period': 'M07', 'periodName': 'July', 'latest': 'true', 'value': '1.579', 'footnotes': [{}]}, {'year': '2025', 'period': 'M06', 'periodName': 'June', 'value': '1.378', 'footnotes': [{}]}, {'year': '2025', 'period': 'M05', 'periodName': 'May', 'value': '1.438', 'footnotes': [{}]}, {'year': '2025', 'period': 'M04', 'periodName': 'April', 'value': '1.515', 'footnotes': [{}]}, {'year': '2025', 'period': 'M03', 'periodName': 'March', 'value': '1.465', 'footnotes': [{}]}]
Data for series ID APU0000708111: [{'year': '2025', 'period': 'M07', 'periodName': 'July', 'latest': 'true', 'value': '3.599', 'footnotes': [{}]}, {'year': '2025', 'period': 'M06', 'periodName': 'June', 'value': '3.775', 'footnotes': [{}]}, {'year': '2025', 'period': 'M05', 'periodName': 'May', 'value': '4.548', 'footnotes': [{}]}, {'year': '2025', 'period': 'M04', 'periodName': 'April', 'value': '5.122', 'footnotes': [{}]}, {'year': '2025', 'period': 'M03', 'periodName': 'March', 'value': '6.227', 'footnotes': [{}]}]
Data for series ID APU0000703213: [{'year': '2025', 'period': 'M07', 'periodName': 'July', 'latest': 'true', 'value': '8.439', 'footnotes': [{}]}, {'year': '2025', 'period': 'M06', 'periodName': 'June', 'value': '8.197', 'footnotes': [{}]}, {'year': '2025', 'period': 'M05', 'periodName': 'May', 'value': '7.875', 'footnotes': [{}]}, {'year': '2025', 'period': 'M04', 'periodName': 'April', 'value': '7.980', 'footnotes': [{}]}, {'year': '2025', 'period': 'M03', 'periodName': 'March', 'value': '8.097', 'footnotes': [{}]}]
Data for series ID APU0000713111: [{'year': '2025', 'period': 'M07', 'periodName': 'July', 'latest': 'true', 'value': '4.641', 'footnotes': [{}]}, {'year': '2025', 'period': 'M06', 'periodName': 'June', 'value': '4.493', 'footnotes': [{}]}, {'year': '2025', 'period': 'M05', 'periodName': 'May', 'value': '4.429', 'footnotes': [{}]}, {'year': '2025', 'period': 'M04', 'periodName': 'April', 'value': '4.440', 'footnotes': [{}]}, {'year': '2025', 'period': 'M03', 'periodName': 'March', 'value': '4.482', 'footnotes': [{}]}]
Data for series ID APU0000714233: [{'year': '2025', 'period': 'M07', 'periodName': 'July', 'latest': 'true', 'value': '1.649', 'footnotes': [{}]}, {'year': '2025', 'period': 'M06', 'periodName': 'June', 'value': '1.588', 'footnotes': [{}]}, {'year': '2025', 'period': 'M05', 'periodName': 'May', 'value': '1.669', 'footnotes': [{}]}, {'year': '2025', 'period': 'M04', 'periodName': 'April', 'value': '1.674', 'footnotes': [{}]}, {'year': '2025', 'period': 'M03', 'periodName': 'March', 'value': '1.640', 'footnotes': [{}]}]
Data for series ID APU0000711311: [{'year': '2025', 'period': 'M06', 'periodName': 'June', 'latest': 'true', 'value': '1.633', 'footnotes': [{}]}, {'year': '2025', 'period': 'M05', 'periodName': 'May', 'value': '1.564', 'footnotes': [{}]}, {'year': '2025', 'period': 'M04', 'periodName': 'April', 'value': '1.485', 'footnotes': [{}]}, {'year': '2025', 'period': 'M03', 'periodName': 'March', 'value': '1.484', 'footnotes': [{}]}, {'year': '2025', 'period': 'M02', 'periodName': 'February', 'value': '1.536', 'footnotes': [{}]}]
Data for series ID APU0000703613: [{'year': '2025', 'period': 'M07', 'periodName': 'July', 'latest': 'true', 'value': '13.554', 'footnotes': [{}]}, {'year': '2025', 'period': 'M06', 'periodName': 'June', 'value': '12.923', 'footnotes': [{}]}, {'year': '2025', 'period': 'M05', 'periodName': 'May', 'value': '12.207', 'footnotes': [{}]}, {'year': '2025', 'period': 'M04', 'periodName': 'April', 'value': '12.326', 'footnotes': [{}]}, {'year': '2025', 'period': 'M03', 'periodName': 'March', 'value': '11.924', 'footnotes': [{}]}]
Data for series ID APU0000711412: [{'year': '2025', 'period': 'M07', 'periodName': 'July', 'latest': 'true', 'value': '1.997', 'footnotes': [{}]}, {'year': '2025', 'period': 'M06', 'periodName': 'June', 'value': '1.882', 'footnotes': [{}]}, {'year': '2025', 'period': 'M05', 'periodName': 'May', 'value': '1.897', 'footnotes': [{}]}, {'year': '2025', 'period': 'M04', 'periodName': 'April', 'value': '1.927', 'footnotes': [{}]}, {'year': '2025', 'period': 'M03', 'periodName': 'March', 'value': '1.983', 'footnotes': [{}]}]
Data for series ID APU0000712311: [{'year': '2025', 'period': 'M07', 'periodName': 'July', 'latest': 'true', 'value': '1.793', 'footnotes': [{}]}, {'year': '2025', 'period': 'M06', 'periodName': 'June', 'value': '1.737', 'footnotes': [{}]}, {'year': '2025', 'period': 'M05', 'periodName': 'May', 'value': '1.705', 'footnotes': [{}]}, {'year': '2025', 'period': 'M04', 'periodName': 'April', 'value': '1.793', 'footnotes': [{}]}, {'year': '2025', 'period': 'M03', 'periodName': 'March', 'value': '1.819', 'footnotes': [{}]}]
Data for series ID APU0000710411: [{'year': '2025', 'period': 'M07', 'periodName': 'July', 'latest': 'true', 'value': '6.374', 'footnotes': [{}]}, {'year': '2025', 'period': 'M06', 'periodName': 'June', 'value': '6.493', 'footnotes': [{}]}, {'year': '2025', 'period': 'M05', 'periodName': 'May', 'value': '6.466', 'footnotes': [{}]}, {'year': '2025', 'period': 'M04', 'periodName': 'April', 'value': '6.229', 'footnotes': [{}]}, {'year': '2025', 'period': 'M03', 'periodName': 'March', 'value': '6.328', 'footnotes': [{}]}]
Data for series ID APU0000FN1102: [{'year': '2025', 'period': 'M07', 'periodName': 'July', 'latest': 'true', 'value': '0.565', 'footnotes': [{}]}, {'year': '2025', 'period': 'M06', 'periodName': 'June', 'value': '0.579', 'footnotes': [{}]}, {'year': '2025', 'period': 'M05', 'periodName': 'May', 'value': '0.558', 'footnotes': [{}]}, {'year': '2025', 'period': 'M04', 'periodName': 'April', 'value': '0.581', 'footnotes': [{}]}, {'year': '2025', 'period': 'M03', 'periodName': 'March', 'value': '0.583', 'footnotes': [{}]}]
Data for series ID APU0000704312: [{'year': '2025', 'period': 'M07', 'periodName': 'July', 'latest': 'true', 'value': '5.685', 'footnotes': [{}]}, {'year': '2025', 'period': 'M06', 'periodName': 'June', 'value': '5.379', 'footnotes': [{}]}, {'year': '2025', 'period': 'M05', 'periodName': 'May', 'value': '5.453', 'footnotes': [{}]}, {'year': '2025', 'period': 'M04', 'periodName': 'April', 'value': '5.473', 'footnotes': [{}]}, {'year': '2025', 'period': 'M03', 'periodName': 'March', 'value': '5.603', 'footnotes': [{}]}]
Data for series ID APU0000703112: [{'year': '2025', 'period': 'M07', 'periodName': 'July', 'latest': 'true', 'value': '6.254', 'footnotes': [{}]}, {'year': '2025', 'period': 'M06', 'periodName': 'June', 'value': '6.120', 'footnotes': [{}]}, {'year': '2025', 'period': 'M05', 'periodName': 'May', 'value': '5.981', 'footnotes': [{}]}, {'year': '2025', 'period': 'M04', 'periodName': 'April', 'value': '5.801', 'footnotes': [{}]}, {'year': '2025', 'period': 'M03', 'periodName': 'March', 'value': '5.790', 'footnotes': [{}]}]
Data for series ID APU0000701322: [{'year': '2025', 'period': 'M07', 'periodName': 'July', 'latest': 'true', 'value': '1.306', 'footnotes': [{}]}, {'year': '2025', 'period': 'M06', 'periodName': 'June', 'value': '1.318', 'footnotes': [{}]}, {'year': '2025', 'period': 'M05', 'periodName': 'May', 'value': '1.322', 'footnotes': [{}]}, {'year': '2025', 'period': 'M04', 'periodName': 'April', 'value': '1.361', 'footnotes': [{}]}, {'year': '2025', 'period': 'M03', 'periodName': 'March', 'value': '1.379', 'footnotes': [{}]}]
Data for series ID APU0000704211: [{'year': '2025', 'period': 'M07', 'periodName': 'July', 'latest': 'true', 'value': '4.607', 'footnotes': [{}]}, {'year': '2025', 'period': 'M06', 'periodName': 'June', 'value': '4.617', 'footnotes': [{}]}, {'year': '2025', 'period': 'M05', 'periodName': 'May', 'value': '4.505', 'footnotes': [{}]}, {'year': '2025', 'period': 'M04', 'periodName': 'April', 'value': '4.454', 'footnotes': [{}]}, {'year': '2025', 'period': 'M03', 'periodName': 'March', 'value': '4.498', 'footnotes': [{}]}]
Data for series ID APU0000702421: [{'year': '2025', 'period': 'M07', 'periodName': 'July', 'latest': 'true', 'value': '5.264', 'footnotes': [{}]}, {'year': '2025', 'period': 'M06', 'periodName': 'June', 'value': '5.108', 'footnotes': [{}]}, {'year': '2025', 'period': 'M05', 'periodName': 'May', 'value': '5.049', 'footnotes': [{}]}, {'year': '2025', 'period': 'M04', 'periodName': 'April', 'value': '4.956', 'footnotes': [{}]}, {'year': '2025', 'period': 'M03', 'periodName': 'March', 'value': '4.863', 'footnotes': [{}]}]
Data for series ID APU0000718311: [{'year': '2025', 'period': 'M07', 'periodName': 'July', 'latest': 'true', 'value': '6.797', 'footnotes': [{}]}, {'year': '2025', 'period': 'M06', 'periodName': 'June', 'value': '6.815', 'footnotes': [{}]}, {'year': '2025', 'period': 'M05', 'periodName': 'May', 'value': '6.731', 'footnotes': [{}]}, {'year': '2025', 'period': 'M04', 'periodName': 'April', 'value': '6.611', 'footnotes': [{}]}, {'year': '2025', 'period': 'M03', 'periodName': 'March', 'value': '6.536', 'footnotes': [{}]}]
Data for series ID APU0000FC1101: [{'year': '2025', 'period': 'M07', 'periodName': 'July', 'latest': 'true', 'value': '6.504', 'footnotes': [{}]}, {'year': '2025', 'period': 'M06', 'periodName': 'June', 'value': '6.342', 'footnotes': [{}]}, {'year': '2025', 'period': 'M05', 'periodName': 'May', 'value': '6.245', 'footnotes': [{}]}, {'year': '2025', 'period': 'M04', 'periodName': 'April', 'value': '6.142', 'footnotes': [{}]}, {'year': '2025', 'period': 'M03', 'periodName': 'March', 'value': '6.137', 'footnotes': [{}]}]
Data for series ID APU0000711211: [{'year': '2025', 'period': 'M07', 'periodName': 'July', 'latest': 'true', 'value': '0.657', 'footnotes': [{}]}, {'year': '2025', 'period': 'M06', 'periodName': 'June', 'value': '0.654', 'footnotes': [{}]}, {'year': '2025', 'period': 'M05', 'periodName': 'May', 'value': '0.655', 'footnotes': [{}]}, {'year': '2025', 'period': 'M04', 'periodName': 'April', 'value': '0.635', 'footnotes': [{}]}, {'year': '2025', 'period': 'M03', 'periodName': 'March', 'value': '0.625', 'footnotes': [{}]}]

In [7]:
response_data

{'status': 'REQUEST_SUCCEEDED',
 'responseTime': 404,
 'message': [],
 'Results': {'series': [{'seriesID': 'APU0000FF1101',
    'data': [{'year': '2025',
      'period': 'M07',
      'periodName': 'July',
      'latest': 'true',
      'value': '4.204',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M06',
      'periodName': 'June',
      'value': '4.239',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M05',
      'periodName': 'May',
      'value': '4.216',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M04',
      'periodName': 'April',
      'value': '4.180',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M03',
      'periodName': 'March',
      'value': '4.160',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M02',
      'periodName': 'February',
      'value': '4.079',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M01',
      'periodName': 'January',
      'value': '3.969',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M12',
      'periodName': 'December',
      'value': '4.104',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M11',
      'periodName': 'November',
      'value': '4.011',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M10',
      'periodName': 'October',
      'value': '4.037',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M09',
      'periodName': 'September',
      'value': '3.974',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M08',
      'periodName': 'August',
      'value': '3.952',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M07',
      'periodName': 'July',
      'value': '3.946',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M06',
      'periodName': 'June',
      'value': '4.046',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M05',
      'periodName': 'May',
      'value': '4.118',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M04',
      'periodName': 'April',
      'value': '4.061',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M03',
      'periodName': 'March',
      'value': '4.106',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M02',
      'periodName': 'February',
      'value': '4.105',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M01',
      'periodName': 'January',
      'value': '4.086',
      'footnotes': [{}]}]},
   {'seriesID': 'APU0000703432',
    'data': [{'year': '2025',
      'period': 'M07',
      'periodName': 'July',
      'latest': 'true',
      'value': '8.188',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M06',
      'periodName': 'June',
      'value': '8.016',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M05',
      'periodName': 'May',
      'value': '7.729',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M04',
      'periodName': 'April',
      'value': '7.733',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M03',
      'periodName': 'March',
      'value': '7.601',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M02',
      'periodName': 'February',
      'value': '7.677',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M01',
      'periodName': 'January',
      'value': '7.318',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M12',
      'periodName': 'December',
      'value': '7.393',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M11',
      'periodName': 'November',
      'value': '7.432',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M10',
      'periodName': 'October',
      'value': '7.177',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M09',
      'periodName': 'September',
      'value': '7.217',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M08',
      'periodName': 'August',
      'value': '7.298',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M07',
      'periodName': 'July',
      'value': '7.145',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M06',
      'periodName': 'June',
      'value': '7.239',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M05',
      'periodName': 'May',
      'value': '7.229',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M04',
      'periodName': 'April',
      'value': '7.197',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M03',
      'periodName': 'March',
      'value': '6.991',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M02',
      'periodName': 'February',
      'value': '6.839',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M01',
      'periodName': 'January',
      'value': '7.001',
      'footnotes': [{}]}]},
   {'seriesID': 'APU0000FL2101',
    'data': [{'year': '2025',
      'period': 'M07',
      'periodName': 'July',
      'latest': 'true',
      'value': '3.006',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M06',
      'periodName': 'June',
      'value': '2.951',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M05',
      'periodName': 'May',
      'value': '2.994',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M04',
      'periodName': 'April',
      'value': '2.915',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M03',
      'periodName': 'March',
      'value': '2.923',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M02',
      'periodName': 'February',
      'value': '2.865',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M01',
      'periodName': 'January',
      'value': '2.831',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M12',
      'periodName': 'December',
      'value': '2.967',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M11',
      'periodName': 'November',
      'value': '3.027',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M10',
      'periodName': 'October',
      'value': '2.933',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M09',
      'periodName': 'September',
      'value': '2.888',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M08',
      'periodName': 'August',
      'value': '2.964',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M07',
      'periodName': 'July',
      'value': '2.874',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M06',
      'periodName': 'June',
      'value': '2.885',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M05',
      'periodName': 'May',
      'value': '2.832',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M04',
      'periodName': 'April',
      'value': '2.845',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M03',
      'periodName': 'March',
      'value': '2.729',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M02',
      'periodName': 'February',
      'value': '2.568',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M01',
      'periodName': 'January',
      'value': '2.592',
      'footnotes': [{}]}]},
   {'seriesID': 'APU0000704212',
    'data': [{'year': '2025',
      'period': 'M07',
      'periodName': 'July',
      'latest': 'true',
      'value': '4.691',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M06',
      'periodName': 'June',
      'value': '4.618',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M05',
      'periodName': 'May',
      'value': '4.601',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M04',
      'periodName': 'April',
      'value': '4.609',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M03',
      'periodName': 'March',
      'value': '4.771',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M02',
      'periodName': 'February',
      'value': '4.558',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M01',
      'periodName': 'January',
      'value': '4.530',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M12',
      'periodName': 'December',
      'value': '4.658',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M11',
      'periodName': 'November',
      'value': '4.874',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M10',
      'periodName': 'October',
      'value': '4.585',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M09',
      'periodName': 'September',
      'value': '4.615',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M08',
      'periodName': 'August',
      'value': '4.622',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M07',
      'periodName': 'July',
      'value': '4.652',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M06',
      'periodName': 'June',
      'value': '4.589',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M05',
      'periodName': 'May',
      'value': '4.634',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M04',
      'periodName': 'April',
      'value': '4.511',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M03',
      'periodName': 'March',
      'value': '4.527',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M02',
      'periodName': 'February',
      'value': '4.377',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M01',
      'periodName': 'January',
      'value': '4.524',
      'footnotes': [{}]}]},
   {'seriesID': 'APU0000702111',
    'data': [{'year': '2025',
      'period': 'M07',
      'periodName': 'July',
      'latest': 'true',
      'value': '1.851',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M06',
      'periodName': 'June',
      'value': '1.864',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M05',
      'periodName': 'May',
      'value': '1.876',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M04',
      'periodName': 'April',
      'value': '1.913',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M03',
      'periodName': 'March',
      'value': '1.880',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M02',
      'periodName': 'February',
      'value': '1.925',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M01',
      'periodName': 'January',
      'value': '1.925',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M12',
      'periodName': 'December',
      'value': '1.912',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M11',
      'periodName': 'November',
      'value': '1.916',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M10',
      'periodName': 'October',
      'value': '1.937',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M09',
      'periodName': 'September',
      'value': '1.976',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M08',
      'periodName': 'August',
      'value': '1.951',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M07',
      'periodName': 'July',
      'value': '1.975',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M06',
      'periodName': 'June',
      'value': '1.973',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M05',
      'periodName': 'May',
      'value': '1.971',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M04',
      'periodName': 'April',
      'value': '1.998',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M03',
      'periodName': 'March',
      'value': '1.997',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M02',
      'periodName': 'February',
      'value': '2.006',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M01',
      'periodName': 'January',
      'value': '2.033',
      'footnotes': [{}]}]},
   {'seriesID': 'APU0000FD3101',
    'data': [{'year': '2025',
      'period': 'M07',
      'periodName': 'July',
      'latest': 'true',
      'value': '4.333',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M06',
      'periodName': 'June',
      'value': '4.264',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M05',
      'periodName': 'May',
      'value': '4.220',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M04',
      'periodName': 'April',
      'value': '4.244',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M03',
      'periodName': 'March',
      'value': '4.341',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M02',
      'periodName': 'February',
      'value': '4.226',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M01',
      'periodName': 'January',
      'value': '4.249',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M12',
      'periodName': 'December',
      'value': '4.308',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M11',
      'periodName': 'November',
      'value': '4.430',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M10',
      'periodName': 'October',
      'value': '4.273',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M09',
      'periodName': 'September',
      'value': '4.328',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M08',
      'periodName': 'August',
      'value': '4.403',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M07',
      'periodName': 'July',
      'value': '4.409',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M06',
      'periodName': 'June',
      'value': '4.397',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M05',
      'periodName': 'May',
      'value': '4.391',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M04',
      'periodName': 'April',
      'value': '4.235',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M03',
      'periodName': 'March',
      'value': '4.256',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M02',
      'periodName': 'February',
      'value': '4.157',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M01',
      'periodName': 'January',
      'value': '4.236',
      'footnotes': [{}]}]},
   {'seriesID': 'APU0000FJ4101',
    'data': [{'year': '2025',
      'period': 'M07',
      'periodName': 'July',
      'latest': 'true',
      'value': '1.556',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M06',
      'periodName': 'June',
      'value': '1.494',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M05',
      'periodName': 'May',
      'value': '1.577',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M04',
      'periodName': 'April',
      'value': '1.538',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M03',
      'periodName': 'March',
      'value': '1.520',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M02',
      'periodName': 'February',
      'value': '1.515',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M01',
      'periodName': 'January',
      'value': '1.489',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M12',
      'periodName': 'December',
      'value': '1.548',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M11',
      'periodName': 'November',
      'value': '1.512',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M10',
      'periodName': 'October',
      'value': '1.618',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M09',
      'periodName': 'September',
      'value': '1.700',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M08',
      'periodName': 'August',
      'value': '1.694',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M07',
      'periodName': 'July',
      'value': '1.682',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M06',
      'periodName': 'June',
      'value': '1.671',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M05',
      'periodName': 'May',
      'value': '1.656',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M04',
      'periodName': 'April',
      'value': '1.641',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M03',
      'periodName': 'March',
      'value': '1.611',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M02',
      'periodName': 'February',
      'value': '1.623',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M01',
      'periodName': 'January',
      'value': '1.560',
      'footnotes': [{}]}]},
   {'seriesID': 'APU0000703512',
    'data': [{'year': '2025',
      'period': 'M07',
      'periodName': 'July',
      'latest': 'true',
      'value': '8.706',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M06',
      'periodName': 'June',
      'value': '8.394',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M05',
      'periodName': 'May',
      'value': '8.199',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M04',
      'periodName': 'April',
      'value': '8.126',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M03',
      'periodName': 'March',
      'value': '8.155',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M02',
      'periodName': 'February',
      'value': '8.128',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M01',
      'periodName': 'January',
      'value': '8.055',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M12',
      'periodName': 'December',
      'value': '7.626',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M11',
      'periodName': 'November',
      'value': '7.626',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M10',
      'periodName': 'October',
      'value': '7.816',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M09',
      'periodName': 'September',
      'value': '8.090',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M08',
      'periodName': 'August',
      'value': '7.966',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M07',
      'periodName': 'July',
      'value': '7.886',
      'footnotes': [{}]}]},
   {'seriesID': 'APU0000703511',
    'data': [{'year': '2025',
      'period': 'M07',
      'periodName': 'July',
      'latest': 'true',
      'value': '8.690',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M06',
      'periodName': 'June',
      'value': '8.457',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M05',
      'periodName': 'May',
      'value': '8.401',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M04',
      'periodName': 'April',
      'value': '8.627',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M03',
      'periodName': 'March',
      'value': '8.554',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M02',
      'periodName': 'February',
      'value': '8.485',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M01',
      'periodName': 'January',
      'value': '8.280',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M12',
      'periodName': 'December',
      'value': '8.136',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M11',
      'periodName': 'November',

In [8]:
if 'Results' in response_data and 'series' in response_data['Results']:
    series_list = response_data['Results']['series']
    response_df = pd.DataFrame([
        {
            'seriesID': series['seriesID'],
            **data_point
        }
        for series in series_list
        for data_point in series['data']
    ])
else:
    print("No data available to convert to DataFrame.")

In [9]:
response_df.to_csv('data/bls_data.csv', index=False)

In [10]:
response_df['seriesID'].value_counts()

seriesID
APU0000FF1101    19
APU0000711211    19
APU0000712311    19
APU0000710411    19
APU0000FN1102    19
APU0000704312    19
APU0000703112    19
APU0000701322    19
APU0000704211    19
APU0000702421    19
APU0000718311    19
APU0000FC1101    19
APU0000FD2101    19
APU0000703432    19
APU0000703311    19
APU0000706111    19
APU0000701111    19
APU0000FN1101    19
APU0000715211    19
APU0000710211    19
APU0000FS1101    19
APU0000704111    19
APU0000702212    19
APU0000714221    19
APU0000711412    19
APU0000703613    19
APU0000701312    19
APU0000703113    19
APU0000FL2101    19
APU0000704212    19
APU0000702111    19
APU0000FD3101    19
APU0000FJ4101    19
APU0000703511    19
APU0000712112    19
APU0000706212    19
APU0000714233    19
APU0000711415    19
APU0000710212    19
APU0000FJ1101    19
APU0000717311    19
APU0000703111    19
APU0000709112    19
APU0000712211    19
APU0000708111    19
APU0000703213    19
APU0000713111    19
APU0000711411    18
APU0000711311    18
APU0000703512    13
Name: count, dtype: int64

In [11]:
response_df['date'] = pd.to_datetime(response_df['periodName'] + ' ' + response_df['year'].astype(str), format='%B %Y')

In [12]:
response_df

          seriesID  year period periodName latest  value footnotes       date
0    APU0000FF1101  2025    M07       July   true  4.204      [{}] 2025-07-01
1    APU0000FF1101  2025    M06       June    NaN  4.239      [{}] 2025-06-01
2    APU0000FF1101  2025    M05        May    NaN  4.216      [{}] 2025-05-01
3    APU0000FF1101  2025    M04      April    NaN  4.180      [{}] 2025-04-01
4    APU0000FF1101  2025    M03      March    NaN  4.160      [{}] 2025-03-01
..             ...   ...    ...        ...    ...    ...       ...        ...
937  APU0000711415  2024    M05        May    NaN  2.259      [{}] 2024-05-01
938  APU0000711415  2024    M04      April    NaN  2.520      [{}] 2024-04-01
939  APU0000711415  2024    M03      March    NaN  2.648      [{}] 2024-03-01
940  APU0000711415  2024    M02   February    NaN  3.049      [{}] 2024-02-01
941  APU0000711415  2024    M01    January    NaN  3.658      [{}] 2024-01-01

[942 rows x 8 columns]

In [13]:
longform_df = response_df.pivot(index='date', columns='seriesID', values='value')
print(longform_df.head())

seriesID   APU0000701111 APU0000701312 APU0000701322 APU0000702111  \
date
2024-01-01         0.554         1.000         1.425         2.033
2024-02-01         0.558         1.001         1.432         2.006
2024-03-01         0.565         1.014         1.420         1.997
2024-04-01         0.574         1.025         1.422         1.998
2024-05-01         0.570         1.002         1.377         1.971

seriesID   APU0000702212 APU0000702421 APU0000703111 APU0000703112  \
date
2024-01-01         2.631         5.019         5.093         5.030
2024-02-01         2.604         5.248         5.213         5.132
2024-03-01         2.585         5.145         5.421         5.132
2024-04-01         2.625         5.121         5.277         5.236
2024-05-01         2.749         5.124         5.331         5.148

seriesID   APU0000703113 APU0000703213  ... APU0000FC1101 APU0000FD2101  \
date                                    ...
2024-01-01         6.778         7.255  ...         5.475         4.412
2024-02-01         6.651         7.513  ...         5.479         4.517
2024-03-01         6.734         7.362  ...         5.522         4.475
2024-04-01         6.809         7.516  ...         5.561         4.487
2024-05-01         6.847         7.531  ...         5.603         4.575

seriesID   APU0000FD3101 APU0000FF1101 APU0000FJ1101 APU0000FJ4101  \
date
2024-01-01         4.236         4.086         3.650         1.560
2024-02-01         4.157         4.105         3.634         1.623
2024-03-01         4.256         4.106         3.597         1.611
2024-04-01         4.235         4.061         3.622         1.641
2024-05-01         4.391         4.118         3.543         1.656

seriesID   APU0000FL2101 APU0000FN1101 APU0000FN1102 APU0000FS1101
date
2024-01-01         2.592         2.214         0.613         4.659
2024-02-01         2.568         2.245         0.581         4.634
2024-03-01         2.729         2.282         0.573         4.484
2024-04-01         2.845         2.277         0.593         4.629
2024-05-01         2.832         2.236         0.563         4.589

[5 rows x 50 columns]

In [14]:
longform_df

seriesID,APU0000701111,APU0000701312,APU0000701322,APU0000702111,APU0000702212,APU0000702421,APU0000703111,APU0000703112,APU0000703113,APU0000703213,...,APU0000FC1101,APU0000FD2101,APU0000FD3101,APU0000FF1101,APU0000FJ1101,APU0000FJ4101,APU0000FL2101,APU0000FN1101,APU0000FN1102,APU0000FS1101
date,,,,,,,,,,,,,,,,,,,,,
2024-01-01,0.554,1.000,1.425,2.033,2.631,5.019,5.093,5.030,6.778,7.255,...,5.475,4.412,4.236,4.086,3.650,1.560,2.592,2.214,0.613,4.659
2024-02-01,0.558,1.001,1.432,2.006,2.604,5.248,5.213,5.132,6.651,7.513,...,5.479,4.517,4.157,4.105,3.634,1.623,2.568,2.245,0.581,4.634
2024-03-01,0.565,1.014,1.420,1.997,2.585,5.145,5.421,5.132,6.734,7.362,...,5.522,4.475,4.256,4.106,3.597,1.611,2.729,2.282,0.573,4.484
2024-04-01,0.574,1.025,1.422,1.998,2.625,5.121,5.277,5.236,6.809,7.516,...,5.561,4.487,4.235,4.061,3.622,1.641,2.845,2.277,0.593,4.629
2024-05-01,0.570,1.002,1.377,1.971,2.749,5.124,5.331,5.148,6.847,7.531,...,5.603,4.575,4.391,4.118,3.543,1.656,2.832,2.236,0.563,4.589
2024-06-01,0.575,1.018,1.435,1.973,2.775,5.017,5.364,5.472,6.893,7.649,...,5.712,4.562,4.397,4.046,3.703,1.671,2.885,2.021,0.564,4.696
2024-07-01,0.574,1.039,1.432,1.975,2.693,5.102,5.470,5.497,7.169,7.781,...,5.799,4.710,4.409,3.946,3.748,1.682,2.874,2.087,0.577,4.897
2024-08-01,0.574,1.085,1.421,1.951,2.674,5.046,5.638,5.577,6.918,7.692,...,5.867,4.691,4.403,3.952,3.765,1.694,2.964,2.056,0.583,4.796
2024-09-01,0.573,1.078,1.431,1.976,2.748,5.173,5.576,5.670,7.223,7.596,...,5.917,4.595,4.328,3.974,3.768,1.700,2.888,1.998,0.576,5.004
2024-10-01,0.566,1.056,1.445,1.937,2.833,4.852,5.586,5.588,7.220,7.301,...,5.887,4.660,4.273,4.037,3.772,1.618,2.933,2.032,0.567,4.937
2024-11-01,0.552,1.061,1.367,1.916,2.724,4.918,5.605,5.628,6.977,7.578,...,5.874,4.560,4.430,4.011,3.866,1.512,3.027,1.982,0.551,4.794
2024-12-01,0.548,1.032,1.380,1.912,2.796,4.773,5.576,5.605,7.124,7.769,...,5.863,4.406,4.308,4.104,3.868,1.548,2.967,1.845,0.541,4.728
2025-01-01,0.561,1.008,1.366,1.925,2.760,4.895,5.495,5.545,7.110,7.694,...,5.820,4.411,4.249,3.969,3.784,1.489,2.831,2.093,0.582,4.912
2025-02-01,0.561,1.030,1.381,1.925,2.759,4.658,5.744,5.625,7.244,8.104,...,5.961,4.428,4.226,4.079,3.798,1.515,2.865,2.101,0.572,4.869
2025-03-01,0.565,1.038,1.379,1.880,2.719,4.863,5.854,5.790,7.476,8.097,...,6.137,4.496,4.341,4.160,3.851,1.520,2.923,2.103,0.583,4.816
2025-04-01,0.557,1.031,1.361,1.913,2.751,4.956,5.996,5.801,7.551,7.980,...,6.142,4.451,4.244,4.180,3.850,1.538,2.915,2.104,0.581,4.780
2025-05-01,0.562,1.067,1.322,1.876,2.602,5.049,6.018,5.981,7.688,7.875,...,6.245,4.451,4.220,4.216,3.777,1.577,2.994,2.129,0.558,4.952
2025-06-01,0.574,1.061,1.318,1.864,2.656,5.108,6.103,6.120,7.672,8.197,...,6.342,4.401,4.264,4.239,3.592,1.494,2.951,2.183,0.579,4.872
2025-07-01,0.557,1.068,1.306,1.851,2.714,5.264,6.338,6.254,8.035,8.439,...,6.504,4.660,4.333,4.204,3.662,1.556,3.006,2.199,0.565,4.797

In [15]:
response_df['seriesID']

0      APU0000FF1101
1      APU0000FF1101
2      APU0000FF1101
3      APU0000FF1101
4      APU0000FF1101
           ...
937    APU0000711415
938    APU0000711415
939    APU0000711415
940    APU0000711415
941    APU0000711415
Name: seriesID, Length: 942, dtype: object

In [16]:
series_name = pd.read_csv('data/series_name.csv', index_col=0)

In [17]:
response_df = response_df.merge(series_name, left_on='seriesID', right_index=True, how='left')
response_df.head()

,seriesID,year,period,periodName,latest,value,footnotes,date,item_name
0,APU0000FF1101,2025,M07,July,true,4.204,[{}],2025-07-01,"Chicken breast, boneless, per lb."
1,APU0000FF1101,2025,M06,June,NaN,4.239,[{}],2025-06-01,"Chicken breast, boneless, per lb."
2,APU0000FF1101,2025,M05,May,NaN,4.216,[{}],2025-05-01,"Chicken breast, boneless, per lb."
3,APU0000FF1101,2025,M04,April,NaN,4.180,[{}],2025-04-01,"Chicken breast, boneless, per lb."
4,APU0000FF1101,2025,M03,March,NaN,4.160,[{}],2025-03-01,"Chicken breast, boneless, per lb."

In [18]:
longform_df = response_df.pivot(index='date', columns='item_name', values='value')
longform_df.head()

item_name,"All Ham (Excluding Canned Ham and Luncheon Slices), per lb.","All Pork Chops, per lb.","All soft drinks, 12 pk, 12 oz., cans, per 12 oz.","All soft drinks, per 2 liters","All uncooked ground beef, per lb.","American processed cheese, per lb.","Bacon, sliced, per lb.","Bananas, per lb.","Beans, dried, any type, all sizes, per lb.","Beef for stew, boneless, per lb.",...,"Rice, white, long grain, uncooked, per lb.","Round roast, USDA Choice, boneless, per lb.","Spaghetti and macaroni, per lb.","Steak, round, USDA Choice, boneless, per lb.","Steak, round, graded and ungraded, excluding USDA Prime and Choice, per lb.","Steak, sirloin, USDA Choice, boneless, per lb.","Strawberries, dry pint, per 12 oz.","Sugar, white, all sizes, per lb.","Tomatoes, field grown, per lb.","Yogurt, per 8 oz."
date,,,,,,,,,,,,,,,,,,,,,
2024-01-01,4.412,4.236,0.613,2.214,5.475,4.904,6.614,0.617,1.589,7.001,...,1.000,6.737,1.425,8.106,NaN,11.637,3.658,0.975,2.146,1.560
2024-02-01,4.517,4.157,0.581,2.245,5.479,4.769,6.560,0.625,1.625,6.839,...,1.001,6.710,1.432,7.883,NaN,11.716,3.049,0.984,2.132,1.623
2024-03-01,4.475,4.256,0.573,2.282,5.522,4.854,6.609,0.629,1.648,6.991,...,1.014,6.974,1.420,8.031,NaN,11.537,2.648,0.984,2.044,1.611
2024-04-01,4.487,4.235,0.593,2.277,5.561,4.776,6.637,0.626,1.647,7.197,...,1.025,6.858,1.422,8.110,NaN,11.662,2.520,1.006,1.962,1.641
2024-05-01,4.575,4.391,0.563,2.236,5.603,4.819,6.818,0.622,1.703,7.229,...,1.002,6.987,1.377,8.247,NaN,11.558,2.259,1.001,1.859,1.656

### Export data for multiple charts

In [19]:
longform_df.to_csv('data/bls_chart.csv')

## Prepare data for table format

### Get the latest rows for percent change

In [20]:
latest_rows = longform_df.tail(2)
latest_rows

item_name,"All Ham (Excluding Canned Ham and Luncheon Slices), per lb.","All Pork Chops, per lb.","All soft drinks, 12 pk, 12 oz., cans, per 12 oz.","All soft drinks, per 2 liters","All uncooked ground beef, per lb.","American processed cheese, per lb.","Bacon, sliced, per lb.","Bananas, per lb.","Beans, dried, any type, all sizes, per lb.","Beef for stew, boneless, per lb.",...,"Rice, white, long grain, uncooked, per lb.","Round roast, USDA Choice, boneless, per lb.","Spaghetti and macaroni, per lb.","Steak, round, USDA Choice, boneless, per lb.","Steak, round, graded and ungraded, excluding USDA Prime and Choice, per lb.","Steak, sirloin, USDA Choice, boneless, per lb.","Strawberries, dry pint, per 12 oz.","Sugar, white, all sizes, per lb.","Tomatoes, field grown, per lb.","Yogurt, per 8 oz."
date,,,,,,,,,,,,,,,,,,,,,
2025-06-01,4.401,4.264,0.579,2.183,6.342,5.038,7.098,0.654,1.588,8.016,...,1.061,7.762,1.318,8.457,8.394,12.923,2.223,1.054,1.737,1.494
2025-07-01,4.660,4.333,0.565,2.199,6.504,4.906,7.118,0.657,1.649,8.188,...,1.068,7.909,1.306,8.690,8.706,13.554,2.221,1.046,1.793,1.556

In [21]:
transposed_latest_rows = latest_rows.transpose()
transposed_latest_rows.head()

date                                               2025-06-01 2025-07-01
item_name
All Ham (Excluding Canned Ham and Luncheon Slic...      4.401      4.660
All Pork Chops, per lb.                                 4.264      4.333
All soft drinks, 12 pk, 12 oz., cans, per 12 oz.        0.579      0.565
All soft drinks, per 2 liters                           2.183      2.199
All uncooked ground beef, per lb.                       6.342      6.504

### Get percentage change

In [22]:
transposed_latest_rows = transposed_latest_rows.dropna()
transposed_latest_rows.head()

date                                               2025-06-01 2025-07-01
item_name
All Ham (Excluding Canned Ham and Luncheon Slic...      4.401      4.660
All Pork Chops, per lb.                                 4.264      4.333
All soft drinks, 12 pk, 12 oz., cans, per 12 oz.        0.579      0.565
All soft drinks, per 2 liters                           2.183      2.199
All uncooked ground beef, per lb.                       6.342      6.504

In [23]:
transposed_latest_rows['change'] = transposed_latest_rows.apply(
    lambda row: ((float(row.iloc[1]) - float(row.iloc[0])) / float(row.iloc[0]) * 100) if pd.notna(row.iloc[0]) and pd.notna(row.iloc[1]) else None,
    axis=1
)
transposed_latest_rows

date,2025-06-01 00:00:00,2025-07-01 00:00:00,change
item_name,,,
"All Ham (Excluding Canned Ham and Luncheon Slices), per lb.",4.401,4.660,5.885026
"All Pork Chops, per lb.",4.264,4.333,1.618199
"All soft drinks, 12 pk, 12 oz., cans, per 12 oz.",0.579,0.565,-2.417962
"All soft drinks, per 2 liters",2.183,2.199,0.732936
"All uncooked ground beef, per lb.",6.342,6.504,2.554399
"American processed cheese, per lb.",5.038,4.906,-2.620087
"Bacon, sliced, per lb.",7.098,7.118,0.281770
"Bananas, per lb.",0.654,0.657,0.458716
"Beans, dried, any type, all sizes, per lb.",1.588,1.649,3.841310
"Beef for stew, boneless, per lb.",8.016,8.188,2.145709
"Bread, white, pan, per lb.",1.864,1.851,-0.697425
"Bread, whole wheat, pan, per lb.",2.656,2.714,2.183735
"Butter, stick, per lb.",4.872,4.797,-1.539409
"Cheddar cheese, natural, per lb.",5.999,6.041,0.700117
"Chicken breast, boneless, per lb.",4.239,4.204,-0.825666
"Chicken legs, bone-in, per lb.",1.815,1.799,-0.881543
"Chicken, fresh, whole, per lb.",2.086,2.078,-0.383509
"Chops, boneless, per lb.",4.618,4.691,1.580771
"Chops, center cut, bone-in, per lb.",4.617,4.607,-0.216591
"Chuck roast, USDA Choice, boneless, per lb.",8.197,8.439,2.952300
"Coffee, 100%, ground roast, all sizes, per lb.",8.132,8.414,3.467782
"Cookies, chocolate chip, per lb.",5.108,5.264,3.054033
"Corn, canned, any style, all sizes, per lb.",1.414,1.415,0.070721
"Eggs, grade A, large, per doz.",3.775,3.599,-4.662252
"Flour, white, all purpose, per lb.",0.574,0.557,-2.961672
"Grapefruit, per lb.",1.715,1.726,0.641399
"Ground beef, 100% beef, per lb.",6.120,6.254,2.189542
"Ground beef, lean and extra lean, per lb.",7.672,8.035,4.731491
"Ground chuck, 100% beef, per lb.",6.103,6.338,3.850565
"Ham, boneless, excluding canned, per lb.",5.379,5.685,5.688790
"Ice cream, prepackaged, bulk, regular, per 1/2 gal.",6.493,6.374,-1.832743
"Lemons, per lb.",1.882,1.997,6.110521
"Lettuce, iceberg, per lb.",1.378,1.579,14.586357
"Lettuce, romaine, per lb.",2.951,3.006,1.863775
"Milk, fresh, low-fat, reduced fat, skim, per gal.",3.592,3.662,1.948775
"Milk, fresh, whole, fortified, per gal.",4.029,4.162,3.301067
"Orange juice, frozen concentrate, 12 oz. can, per 16 oz.",4.493,4.641,3.294013
"Potato chips, per 16 oz.",6.815,6.797,-0.264123
"Potatoes, white, per lb.",0.981,0.978,-0.305810
"Rice, white, long grain, uncooked, per lb.",1.061,1.068,0.659755
"Round roast, USDA Choice, boneless, per lb.",7.762,7.909,1.893842
"Spaghetti and macaroni, per lb.",1.318,1.306,-0.910470
"Steak, round, USDA Choice, boneless, per lb.",8.457,8.690,2.755114
"Steak, round, graded and ungraded, excluding USDA Prime and Choice, per lb.",8.394,8.706,3.716941
"Steak, sirloin, USDA Choice, boneless, per lb.",12.923,13.554,4.882767
"Strawberries, dry pint, per 12 oz.",2.223,2.221,-0.089969
"Sugar, white, all sizes, per lb.",1.054,1.046,-0.759013
"Tomatoes, field grown, per lb.",1.737,1.793,3.223949
"Yogurt, per 8 oz.",1.494,1.556,4.149933

### Export table

In [24]:
transposed_latest_rows.to_csv('data/bls_table.csv')

## Consumer Price Index

In [112]:
data = {
    "seriesid": ['CUSR0000SA0'],  
    "startyear": "2020",
    "endyear": "2025",
    "registrationkey": api_key
}

response = requests.post(url, data=json.dumps(data), headers=headers)
response_data = response.json()

In [113]:
response_data

{'status': 'REQUEST_SUCCEEDED',
 'responseTime': 84,
 'message': [],
 'Results': {'series': [{'seriesID': 'CUSR0000SA0',
    'data': [{'year': '2025',
      'period': 'M07',
      'periodName': 'July',
      'latest': 'true',
      'value': '322.132',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M06',
      'periodName': 'June',
      'value': '321.500',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M05',
      'periodName': 'May',
      'value': '320.580',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M04',
      'periodName': 'April',
      'value': '320.321',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M03',
      'periodName': 'March',
      'value': '319.615',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M02',
      'periodName': 'February',
      'value': '319.775',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M01',
      'periodName': 'January',
      'value': '319.086',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M12',
      'periodName': 'December',
      'value': '317.603',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M11',
      'periodName': 'November',
      'value': '316.449',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M10',
      'periodName': 'October',
      'value': '315.564',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M09',
      'periodName': 'September',
      'value': '314.851',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M08',
      'periodName': 'August',
      'value': '314.131',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M07',
      'periodName': 'July',
      'value': '313.566',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M06',
      'periodName': 'June',
      'value': '313.131',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M05',
      'periodName': 'May',
      'value': '313.140',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M04',
      'periodName': 'April',
      'value': '313.016',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M03',
      'periodName': 'March',
      'value': '312.107',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M02',
      'periodName': 'February',
      'value': '311.022',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M01',
      'periodName': 'January',
      'value': '309.794',
      'footnotes': [{}]},
     {'year': '2023',
      'period': 'M12',
      'periodName': 'December',
      'value': '308.735',
      'footnotes': [{}]},
     {'year': '2023',
      'period': 'M11',
      'periodName': 'November',
      'value': '308.087',
      'footnotes': [{}]},
     {'year': '2023',
      'period': 'M10',
      'periodName': 'October',
      'value': '307.653',
      'footnotes': [{}]},
     {'year': '2023',
      'period': 'M09',
      'periodName': 'September',
      'value': '307.374',
      'footnotes': [{}]},
     {'year': '2023',
      'period': 'M08',
      'periodName': 'August',
      'value': '306.138',
      'footnotes': [{}]},
     {'year': '2023',
      'period': 'M07',
      'periodName': 'July',
      'value': '304.615',
      'footnotes': [{}]},
     {'year': '2023',
      'period': 'M06',
      'periodName': 'June',
      'value': '304.099',
      'footnotes': [{}]},
     {'year': '2023',
      'period': 'M05',
      'periodName': 'May',
      'value': '303.316',
      'footnotes': [{}]},
     {'year': '2023',
      'period': 'M04',
      'periodName': 'April',
      'value': '302.858',
      'footnotes': [{}]},
     {'year': '2023',
      'period': 'M03',
      'periodName': 'March',
      'value': '301.643',
      'footnotes': [{}]},
     {'year': '2023',
      'period': 'M02',
      'periodName': 'February',
      'value': '301.476',
      'footnotes': [{}]},
     {'year': '2023',
      'period': 'M01',
      'periodName': 'January',
      'value': '300.456',
      'footnotes': [{}]},
     {'year': '2022',
      'period': 'M12',
      'periodName': 'December',
      'value': '298.808',
      'footnotes': [{}]},
     {'year': '2022',
      'period': 'M11',
      'periodName': 'November',
      'value': '298.708',
      'footnotes': [{}]},
     {'year': '2022',
      'period': 'M10',
      'periodName': 'October',
      'value': '297.979',
      'footnotes': [{}]},
     {'year': '2022',
      'period': 'M09',
      'periodName': 'September',
      'value': '296.421',
      'footnotes': [{}]},
     {'year': '2022',
      'period': 'M08',
      'periodName': 'August',
      'value': '295.162',
      'footnotes': [{}]},
     {'year': '2022',
      'period': 'M07',
      'periodName': 'July',
      'value': '294.940',
      'footnotes': [{}]},
     {'year': '2022',
      'period': 'M06',
      'periodName': 'June',
      'value': '295.072',
      'footnotes': [{}]},
     {'year': '2022',
      'period': 'M05',
      'periodName': 'May',
      'value': '291.299',
      'footnotes': [{}]},
     {'year': '2022',
      'period': 'M04',
      'periodName': 'April',
      'value': '288.582',
      'footnotes': [{}]},
     {'year': '2022',
      'period': 'M03',
      'periodName': 'March',
      'value': '287.467',
      'footnotes': [{}]},
     {'year': '2022',
      'period': 'M02',
      'periodName': 'February',
      'value': '284.525',
      'footnotes': [{}]},
     {'year': '2022',
      'period': 'M01',
      'periodName': 'January',
      'value': '282.542',
      'footnotes': [{}]},
     {'year': '2021',
      'period': 'M12',
      'periodName': 'December',
      'value': '280.806',
      'footnotes': [{}]},
     {'year': '2021',
      'period': 'M11',
      'periodName': 'November',
      'value': '278.824',
      'footnotes': [{}]},
     {'year': '2021',
      'period': 'M10',
      'periodName': 'October',
      'value': '276.528',
      'footnotes': [{}]},
     {'year': '2021',
      'period': 'M09',
      'periodName': 'September',
      'value': '273.942',
      'footnotes': [{}]},
     {'year': '2021',
      'period': 'M08',
      'periodName': 'August',
      'value': '272.752',
      'footnotes': [{}]},
     {'year': '2021',
      'period': 'M07',
      'periodName': 'July',
      'value': '271.965',
      'footnotes': [{}]},
     {'year': '2021',
      'period': 'M06',
      'periodName': 'June',
      'value': '270.710',
      'footnotes': [{}]},
     {'year': '2021',
      'period': 'M05',
      'periodName': 'May',
      'value': '268.404',
      'footnotes': [{}]},
     {'year': '2021',
      'period': 'M04',
      'periodName': 'April',
      'value': '266.625',
      'footnotes': [{}]},
     {'year': '2021',
      'period': 'M03',
      'periodName': 'March',
      'value': '264.847',
      'footnotes': [{}]},
     {'year': '2021',
      'period': 'M02',
      'periodName': 'February',
      'value': '263.573',
      'footnotes': [{}]},
     {'year': '2021',
      'period': 'M01',
      'periodName': 'January',
      'value': '262.639',
      'footnotes': [{}]},
     {'year': '2020',
      'period': 'M12',
      'periodName': 'December',
      'value': '262.045',
      'footnotes': [{}]},
     {'year': '2020',
      'period': 'M11',
      'periodName': 'November',
      'value': '260.911',
      'footnotes': [{}]},
     {'year': '2020',
      'period': 'M10',
      'periodName': 'October',
      'value': '260.319',
      'footnotes': [{}]},
     {'year': '2020',
      'period': 'M09',
      'periodName': 'September',
      'value': '259.997',
      'footnotes': [{}]},
     {'year': '2020',
      'period': 'M08',
      'periodName': 'August',
      'value': '259.316',
      'footnotes': [{}]},
     {'year': '2020',
      'period': 'M07',
      'periodName': 'July',
      'value': '258.352',
      'footnotes': [{}]},
     {'year': '2020',
      'period': 'M06',
      'periodName': 'June',
      'value': '257.042',
      'footnotes': [{}]},
     {'year': '2020',
      'period': 'M05',
      'periodName': 'May',
      'value': '255.802',
      'footnotes': [{}]},
     {'year': '2020',
      'period': 'M04',
      'periodName': 'April',
      'value': '256.032',
      'footnotes': [{}]},
     {'year': '2020',
      'period': 'M03',
      'periodName': 'March',
      'value': '258.076',
      'footnotes': [{}]},
     {'year': '2020',
      'period': 'M02',
      'periodName': 'February',
      'value': '259.250',
      'footnotes': [{}]},
     {'year': '2020',
      'period': 'M01',
      'periodName': 'January',
      'value': '259.127',
      'footnotes': [{}]}]}]}}

In [114]:
series_data = response_data['Results']['series'][0]['data']

# Convert to DataFrame for easier manipulation
df = pd.DataFrame(series_data)
df['value'] = pd.to_numeric(df['value'])
df['date'] = pd.to_datetime(df['year'] + '-' + df['period'].str.replace('M', '') + '-01')
df = df.sort_values('date')

# Calculate 12-month percentage change
df['CPI'] = df['value'].pct_change(periods=12) * 100

print(df[['date', 'value', 'CPI']].tail())

        date    value       CPI
4 2025-03-01  319.615  2.405585
3 2025-04-01  320.321  2.333747
2 2025-05-01  320.580  2.375934
1 2025-06-01  321.500  2.672683
0 2025-07-01  322.132  2.731801

In [115]:
df = df[df['year'] != '2020']

In [116]:
df.head()

    year period periodName latest    value footnotes       date       CPI
54  2021    M01    January    NaN  262.639      [{}] 2021-01-01  1.355320
53  2021    M02   February    NaN  263.573      [{}] 2021-02-01  1.667502
52  2021    M03      March    NaN  264.847      [{}] 2021-03-01  2.623646
51  2021    M04      April    NaN  266.625      [{}] 2021-04-01  4.137373
50  2021    M05        May    NaN  268.404      [{}] 2021-05-01  4.926467

In [117]:
df.to_csv('data/cpi_inflation.csv', index=False)

## Core inflation

In [118]:
data = {
    "seriesid": ['CUSR0000SA0L1E'],  
    "startyear": "2020",
    "endyear": "2025",
    "registrationkey": api_key
}

response = requests.post(url, data=json.dumps(data), headers=headers)
response_data = response.json()

In [119]:
response_data

{'status': 'REQUEST_SUCCEEDED',
 'responseTime': 95,
 'message': [],
 'Results': {'series': [{'seriesID': 'CUSR0000SA0L1E',
    'data': [{'year': '2025',
      'period': 'M07',
      'periodName': 'July',
      'latest': 'true',
      'value': '328.656',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M06',
      'periodName': 'June',
      'value': '327.600',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M05',
      'periodName': 'May',
      'value': '326.854',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M04',
      'periodName': 'April',
      'value': '326.430',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M03',
      'periodName': 'March',
      'value': '325.659',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M02',
      'periodName': 'February',
      'value': '325.475',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M01',
      'periodName': 'January',
      'value': '324.739',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M12',
      'periodName': 'December',
      'value': '323.296',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M11',
      'periodName': 'November',
      'value': '322.619',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M10',
      'periodName': 'October',
      'value': '321.688',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M09',
      'periodName': 'September',
      'value': '320.835',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M08',
      'periodName': 'August',
      'value': '319.839',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M07',
      'periodName': 'July',
      'value': '318.933',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M06',
      'periodName': 'June',
      'value': '318.343',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M05',
      'periodName': 'May',
      'value': '318.053',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M04',
      'periodName': 'April',
      'value': '317.596',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M03',
      'periodName': 'March',
      'value': '316.762',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M02',
      'periodName': 'February',
      'value': '315.555',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M01',
      'periodName': 'January',
      'value': '314.389',
      'footnotes': [{}]},
     {'year': '2023',
      'period': 'M12',
      'periodName': 'December',
      'value': '313.230',
      'footnotes': [{}]},
     {'year': '2023',
      'period': 'M11',
      'periodName': 'November',
      'value': '312.373',
      'footnotes': [{}]},
     {'year': '2023',
      'period': 'M10',
      'periodName': 'October',
      'value': '311.433',
      'footnotes': [{}]},
     {'year': '2023',
      'period': 'M09',
      'periodName': 'September',
      'value': '310.616',
      'footnotes': [{}]},
     {'year': '2023',
      'period': 'M08',
      'periodName': 'August',
      'value': '309.646',
      'footnotes': [{}]},
     {'year': '2023',
      'period': 'M07',
      'periodName': 'July',
      'value': '308.959',
      'footnotes': [{}]},
     {'year': '2023',
      'period': 'M06',
      'periodName': 'June',
      'value': '308.291',
      'footnotes': [{}]},
     {'year': '2023',
      'period': 'M05',
      'periodName': 'May',
      'value': '307.623',
      'footnotes': [{}]},
     {'year': '2023',
      'period': 'M04',
      'periodName': 'April',
      'value': '306.490',
      'footnotes': [{}]},
     {'year': '2023',
      'period': 'M03',
      'periodName': 'March',
      'value': '305.123',
      'footnotes': [{}]},
     {'year': '2023',
      'period': 'M02',
      'periodName': 'February',
      'value': '304.097',
      'footnotes': [{}]},
     {'year': '2023',
      'period': 'M01',
      'periodName': 'January',
      'value': '302.685',
      'footnotes': [{}]},
     {'year': '2022',
      'period': 'M12',
      'periodName': 'December',
      'value': '301.433',
      'footnotes': [{}]},
     {'year': '2022',
      'period': 'M11',
      'periodName': 'November',
      'value': '300.316',
      'footnotes': [{}]},
     {'year': '2022',
      'period': 'M10',
      'periodName': 'October',
      'value': '299.381',
      'footnotes': [{}]},
     {'year': '2022',
      'period': 'M09',
      'periodName': 'September',
      'value': '298.281',
      'footnotes': [{}]},
     {'year': '2022',
      'period': 'M08',
      'periodName': 'August',
      'value': '296.582',
      'footnotes': [{}]},
     {'year': '2022',
      'period': 'M07',
      'periodName': 'July',
      'value': '295.080',
      'footnotes': [{}]},
     {'year': '2022',
      'period': 'M06',
      'periodName': 'June',
      'value': '294.009',
      'footnotes': [{}]},
     {'year': '2022',
      'period': 'M05',
      'periodName': 'May',
      'value': '292.039',
      'footnotes': [{}]},
     {'year': '2022',
      'period': 'M04',
      'periodName': 'April',
      'value': '290.474',
      'footnotes': [{}]},
     {'year': '2022',
      'period': 'M03',
      'periodName': 'March',
      'value': '289.044',
      'footnotes': [{}]},
     {'year': '2022',
      'period': 'M02',
      'periodName': 'February',
      'value': '288.256',
      'footnotes': [{}]},
     {'year': '2022',
      'period': 'M01',
      'periodName': 'January',
      'value': '286.799',
      'footnotes': [{}]},
     {'year': '2021',
      'period': 'M12',
      'periodName': 'December',
      'value': '285.221',
      'footnotes': [{}]},
     {'year': '2021',
      'period': 'M11',
      'periodName': 'November',
      'value': '283.411',
      'footnotes': [{}]},
     {'year': '2021',
      'period': 'M10',
      'periodName': 'October',
      'value': '281.649',
      'footnotes': [{}]},
     {'year': '2021',
      'period': 'M09',
      'periodName': 'September',
      'value': '279.727',
      'footnotes': [{}]},
     {'year': '2021',
      'period': 'M08',
      'periodName': 'August',
      'value': '279.021',
      'footnotes': [{}]},
     {'year': '2021',
      'period': 'M07',
      'periodName': 'July',
      'value': '278.639',
      'footnotes': [{}]},
     {'year': '2021',
      'period': 'M06',
      'periodName': 'June',
      'value': '277.608',
      'footnotes': [{}]},
     {'year': '2021',
      'period': 'M05',
      'periodName': 'May',
      'value': '275.457',
      'footnotes': [{}]},
     {'year': '2021',
      'period': 'M04',
      'periodName': 'April',
      'value': '273.626',
      'footnotes': [{}]},
     {'year': '2021',
      'period': 'M03',
      'periodName': 'March',
      'value': '271.453',
      'footnotes': [{}]},
     {'year': '2021',
      'period': 'M02',
      'periodName': 'February',
      'value': '270.776',
      'footnotes': [{}]},
     {'year': '2021',
      'period': 'M01',
      'periodName': 'January',
      'value': '270.416',
      'footnotes': [{}]},
     {'year': '2020',
      'period': 'M12',
      'periodName': 'December',
      'value': '270.341',
      'footnotes': [{}]},
     {'year': '2020',
      'period': 'M11',
      'periodName': 'November',
      'value': '269.981',
      'footnotes': [{}]},
     {'year': '2020',
      'period': 'M10',
      'periodName': 'October',
      'value': '269.306',
      'footnotes': [{}]},
     {'year': '2020',
      'period': 'M09',
      'periodName': 'September',
      'value': '268.933',
      'footnotes': [{}]},
     {'year': '2020',
      'period': 'M08',
      'periodName': 'August',
      'value': '268.422',
      'footnotes': [{}]},
     {'year': '2020',
      'period': 'M07',
      'periodName': 'July',
      'value': '267.389',
      'footnotes': [{}]},
     {'year': '2020',
      'period': 'M06',
      'periodName': 'June',
      'value': '265.849',
      'footnotes': [{}]},
     {'year': '2020',
      'period': 'M05',
      'periodName': 'May',
      'value': '265.412',
      'footnotes': [{}]},
     {'year': '2020',
      'period': 'M04',
      'periodName': 'April',
      'value': '265.746',
      'footnotes': [{}]},
     {'year': '2020',
      'period': 'M03',
      'periodName': 'March',
      'value': '267.054',
      'footnotes': [{}]},
     {'year': '2020',
      'period': 'M02',
      'periodName': 'February',
      'value': '267.370',
      'footnotes': [{}]},
     {'year': '2020',
      'period': 'M01',
      'periodName': 'January',
      'value': '266.716',
      'footnotes': [{}]}]}]}}

In [120]:
series_data = response_data['Results']['series'][0]['data']

# Convert to DataFrame for easier manipulation
df = pd.DataFrame(series_data)
df['value'] = pd.to_numeric(df['value'])
df['date'] = pd.to_datetime(df['year'] + '-' + df['period'].str.replace('M', '') + '-01')
df = df.sort_values('date')

# Calculate 12-month percentage change
df['Core CPI'] = df['value'].pct_change(periods=12) * 100

print(df[['date', 'value', 'Core CPI']].tail())

        date    value  Core CPI
4 2025-03-01  325.659  2.808733
3 2025-04-01  326.430  2.781521
2 2025-05-01  326.854  2.767149
1 2025-06-01  327.600  2.907870
0 2025-07-01  328.656  3.048603

In [121]:
df = df[df['year'] != '2020']

In [122]:
df.head()

    year period periodName latest    value footnotes       date  Core CPI
54  2021    M01    January    NaN  270.416      [{}] 2021-01-01  1.387243
53  2021    M02   February    NaN  270.776      [{}] 2021-02-01  1.273890
52  2021    M03      March    NaN  271.453      [{}] 2021-03-01  1.647232
51  2021    M04      April    NaN  273.626      [{}] 2021-04-01  2.965237
50  2021    M05        May    NaN  275.457      [{}] 2021-05-01  3.784682

In [123]:
df.to_csv('data/cpi_core.csv', index=False)

## Food index

In [124]:
data = {
    "seriesid": ['CUSR0000SAF1'],  # Food index, seasonally adjusted
    "startyear": "2020",
    "endyear": "2025",
    "registrationkey": api_key
}

In [125]:
response = requests.post(url, data=json.dumps(data), headers=headers)
response_data = response.json()

In [126]:
response_data

{'status': 'REQUEST_SUCCEEDED',
 'responseTime': 86,
 'message': [],
 'Results': {'series': [{'seriesID': 'CUSR0000SAF1',
    'data': [{'year': '2025',
      'period': 'M07',
      'periodName': 'July',
      'latest': 'true',
      'value': '339.652',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M06',
      'periodName': 'June',
      'value': '339.498',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M05',
      'periodName': 'May',
      'value': '338.386',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M04',
      'periodName': 'April',
      'value': '337.424',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M03',
      'periodName': 'March',
      'value': '337.686',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M02',
      'periodName': 'February',
      'value': '336.223',
      'footnotes': [{}]},
     {'year': '2025',
      'period': 'M01',
      'periodName': 'January',
      'value': '335.671',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M12',
      'periodName': 'December',
      'value': '334.456',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M11',
      'periodName': 'November',
      'value': '333.492',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M10',
      'periodName': 'October',
      'value': '332.418',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M09',
      'periodName': 'September',
      'value': '331.716',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M08',
      'periodName': 'August',
      'value': '330.644',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M07',
      'periodName': 'July',
      'value': '330.142',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M06',
      'periodName': 'June',
      'value': '329.651',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M05',
      'periodName': 'May',
      'value': '328.864',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M04',
      'periodName': 'April',
      'value': '328.413',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M03',
      'periodName': 'March',
      'value': '328.004',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M02',
      'periodName': 'February',
      'value': '327.803',
      'footnotes': [{}]},
     {'year': '2024',
      'period': 'M01',
      'periodName': 'January',
      'value': '327.575',
      'footnotes': [{}]},
     {'year': '2023',
      'period': 'M12',
      'periodName': 'December',
      'value': '326.442',
      'footnotes': [{}]},
     {'year': '2023',
      'period': 'M11',
      'periodName': 'November',
      'value': '325.808',
      'footnotes': [{}]},
     {'year': '2023',
      'period': 'M10',
      'periodName': 'October',
      'value': '325.424',
      'footnotes': [{}]},
     {'year': '2023',
      'period': 'M09',
      'periodName': 'September',
      'value': '324.332',
      'footnotes': [{}]},
     {'year': '2023',
      'period': 'M08',
      'periodName': 'August',
      'value': '323.957',
      'footnotes': [{}]},
     {'year': '2023',
      'period': 'M07',
      'periodName': 'July',
      'value': '323.046',
      'footnotes': [{}]},
     {'year': '2023',
      'period': 'M06',
      'periodName': 'June',
      'value': '322.406',
      'footnotes': [{}]},
     {'year': '2023',
      'period': 'M05',
      'periodName': 'May',
      'value': '321.933',
      'footnotes': [{}]},
     {'year': '2023',
      'period': 'M04',
      'periodName': 'April',
      'value': '321.209',
      'footnotes': [{}]},
     {'year': '2023',
      'period': 'M03',
      'periodName': 'March',
      'value': '320.797',
      'footnotes': [{}]},
     {'year': '2023',
      'period': 'M02',
      'periodName': 'February',
      'value': '320.651',
      'footnotes': [{}]},
     {'year': '2023',
      'period': 'M01',
      'periodName': 'January',
      'value': '319.421',
      'footnotes': [{}]},
     {'year': '2022',
      'period': 'M12',
      'periodName': 'December',
      'value': '317.798',
      'footnotes': [{}]},
     {'year': '2022',
      'period': 'M11',
      'periodName': 'November',
      'value': '316.500',
      'footnotes': [{}]},
     {'year': '2022',
      'period': 'M10',
      'periodName': 'October',
      'value': '315.023',
      'footnotes': [{}]},
     {'year': '2022',
      'period': 'M09',
      'periodName': 'September',
      'value': '312.835',
      'footnotes': [{}]},
     {'year': '2022',
      'period': 'M08',
      'periodName': 'August',
      'value': '310.739',
      'footnotes': [{}]},
     {'year': '2022',
      'period': 'M07',
      'periodName': 'July',
      'value': '308.083',
      'footnotes': [{}]},
     {'year': '2022',
      'period': 'M06',
      'periodName': 'June',
      'value': '304.845',
      'footnotes': [{}]},
     {'year': '2022',
      'period': 'M05',
      'periodName': 'May',
      'value': '301.684',
      'footnotes': [{}]},
     {'year': '2022',
      'period': 'M04',
      'periodName': 'April',
      'value': '298.363',
      'footnotes': [{}]},
     {'year': '2022',
      'period': 'M03',
      'periodName': 'March',
      'value': '295.713',
      'footnotes': [{}]},
     {'year': '2022',
      'period': 'M02',
      'periodName': 'February',
      'value': '292.978',
      'footnotes': [{}]},
     {'year': '2022',
      'period': 'M01',
      'periodName': 'January',
      'value': '290.144',
      'footnotes': [{}]},
     {'year': '2021',
      'period': 'M12',
      'periodName': 'December',
      'value': '287.798',
      'footnotes': [{}]},
     {'year': '2021',
      'period': 'M11',
      'periodName': 'November',
      'value': '286.057',
      'footnotes': [{}]},
     {'year': '2021',
      'period': 'M10',
      'periodName': 'October',
      'value': '283.972',
      'footnotes': [{}]},
     {'year': '2021',
      'period': 'M09',
      'periodName': 'September',
      'value': '281.299',
      'footnotes': [{}]},
     {'year': '2021',
      'period': 'M08',
      'periodName': 'August',
      'value': '278.985',
      'footnotes': [{}]},
     {'year': '2021',
      'period': 'M07',
      'periodName': 'July',
      'value': '277.759',
      'footnotes': [{}]},
     {'year': '2021',
      'period': 'M06',
      'periodName': 'June',
      'value': '276.002',
      'footnotes': [{}]},
     {'year': '2021',
      'period': 'M05',
      'periodName': 'May',
      'value': '273.890',
      'footnotes': [{}]},
     {'year': '2021',
      'period': 'M04',
      'periodName': 'April',
      'value': '272.761',
      'footnotes': [{}]},
     {'year': '2021',
      'period': 'M03',
      'periodName': 'March',
      'value': '271.756',
      'footnotes': [{}]},
     {'year': '2021',
      'period': 'M02',
      'periodName': 'February',
      'value': '271.498',
      'footnotes': [{}]},
     {'year': '2021',
      'period': 'M01',
      'periodName': 'January',
      'value': '271.223',
      'footnotes': [{}]},
     {'year': '2020',
      'period': 'M12',
      'periodName': 'December',
      'value': '270.781',
      'footnotes': [{}]},
     {'year': '2020',
      'period': 'M11',
      'periodName': 'November',
      'value': '269.636',
      'footnotes': [{}]},
     {'year': '2020',
      'period': 'M10',
      'periodName': 'October',
      'value': '269.653',
      'footnotes': [{}]},
     {'year': '2020',
      'period': 'M09',
      'periodName': 'September',
      'value': '269.043',
      'footnotes': [{}]},
     {'year': '2020',
      'period': 'M08',
      'periodName': 'August',
      'value': '268.957',
      'footnotes': [{}]},
     {'year': '2020',
      'period': 'M07',
      'periodName': 'July',
      'value': '268.532',
      'footnotes': [{}]},
     {'year': '2020',
      'period': 'M06',
      'periodName': 'June',
      'value': '269.553',
      'footnotes': [{}]},
     {'year': '2020',
      'period': 'M05',
      'periodName': 'May',
      'value': '268.086',
      'footnotes': [{}]},
     {'year': '2020',
      'period': 'M04',
      'periodName': 'April',
      'value': '266.370',
      'footnotes': [{}]},
     {'year': '2020',
      'period': 'M03',
      'periodName': 'March',
      'value': '262.622',
      'footnotes': [{}]},
     {'year': '2020',
      'period': 'M02',
      'periodName': 'February',
      'value': '261.962',
      'footnotes': [{}]},
     {'year': '2020',
      'period': 'M01',
      'periodName': 'January',
      'value': '261.293',
      'footnotes': [{}]}]}]}}

In [127]:
series_data = response_data['Results']['series'][0]['data']

# Convert to DataFrame for easier manipulation
df = pd.DataFrame(series_data)
df['value'] = pd.to_numeric(df['value'])
df['date'] = pd.to_datetime(df['year'] + '-' + df['period'].str.replace('M', '') + '-01')
df = df.sort_values('date')

# Calculate 12-month percentage change
df['Food index'] = df['value'].pct_change(periods=12) * 100

print(df[['date', 'value', 'Food index']].tail())

        date    value  Food index
4 2025-03-01  337.686    2.951793
3 2025-04-01  337.424    2.743801
2 2025-05-01  338.386    2.895422
1 2025-06-01  339.498    2.987098
0 2025-07-01  339.652    2.880579

In [128]:
df = df[df['year'] != '2020']

In [129]:
df.to_csv('data/cpi_food.csv', index=False)

## Combine Data

In [133]:
cpi = pd.read_csv('data/cpi_inflation.csv')
cpi_core = pd.read_csv('data/cpi_core.csv')
food_index = pd.read_csv('data/cpi_food.csv')

In [131]:
merged_cpi = cpi.merge(cpi_core, on='date', how='inner', suffixes=('_cpi', '_core'))
merged_cpi.head()

,year_cpi,period_cpi,periodName_cpi,latest_cpi,value_cpi,footnotes_cpi,date,CPI,year_core,period_core,periodName_core,latest_core,value_core,footnotes_core,Core CPI
0,2021,M01,January,NaN,262.639,[{}],2021-01-01,1.355320,2021,M01,January,NaN,270.416,[{}],1.387243
1,2021,M02,February,NaN,263.573,[{}],2021-02-01,1.667502,2021,M02,February,NaN,270.776,[{}],1.273890
2,2021,M03,March,NaN,264.847,[{}],2021-03-01,2.623646,2021,M03,March,NaN,271.453,[{}],1.647232
3,2021,M04,April,NaN,266.625,[{}],2021-04-01,4.137373,2021,M04,April,NaN,273.626,[{}],2.965237
4,2021,M05,May,NaN,268.404,[{}],2021-05-01,4.926467,2021,M05,May,NaN,275.457,[{}],3.784682

In [132]:
merged_cpi.to_csv('data/cpi_merged.csv', index=False)

In [134]:
food_index = pd.read_csv('data/cpi_food.csv')
cpi = pd.read_csv('data/cpi_inflation.csv')

merged_food_cpi = food_index.merge(cpi, on='date', how='inner', suffixes=('_food', '_cpi'))
merged_food_cpi.head()

,year_food,period_food,periodName_food,latest_food,value_food,footnotes_food,date,Food index,year_cpi,period_cpi,periodName_cpi,latest_cpi,value_cpi,footnotes_cpi,CPI
0,2021,M01,January,NaN,271.223,[{}],2021-01-01,3.800331,2021,M01,January,NaN,262.639,[{}],1.355320
1,2021,M02,February,NaN,271.498,[{}],2021-02-01,3.640223,2021,M02,February,NaN,263.573,[{}],1.667502
2,2021,M03,March,NaN,271.756,[{}],2021-03-01,3.478003,2021,M03,March,NaN,264.847,[{}],2.623646
3,2021,M04,April,NaN,272.761,[{}],2021-04-01,2.399294,2021,M04,April,NaN,266.625,[{}],4.137373
4,2021,M05,May,NaN,273.890,[{}],2021-05-01,2.164977,2021,M05,May,NaN,268.404,[{}],4.926467

In [135]:
merged_food_cpi.to_csv('data/cpi_food_merged.csv', index=False)